services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon-streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
